all:
  vars:
    monero_user_name: monero
    volume_mountpoint: /mnt/monero
  children:
    hetzner_nodes:
      hosts:
        hetznernode1:
    digitalocean_nodes:
      hosts:
    vultr_nodes:
      hosts:
    preexisting_nodes:
      hosts: