collections:
  # Install a collection from Ansible Galaxy.
  - name: hetzner.hcloud

  - name: community.general

  # At the point of writing this, the last release of the DigitalOcean collection
  # doesn't support resizing volumes. I've proposed a patch that's waiting to be 
  # merged (https://github.com/ansible-collections/community.digitalocean/pull/39).
  # We can install referencing this patch to be able to get the feature.
  - name: https://github.com/lalvarezguillen/community.digitalocean
    type: git
    version: d0710ba895b6cd21d02add95e74cb611ce8b1948
  
  # At the point of writing this, the last release of the Vultr's collection doesn't
  # support mounting volumes on servers, or resizing volumes. They've accepted
  # a patch I crafted (https://github.com/ngine-io/ansible-collection-vultr/commit/dcb398fccc8ba5b1ed0259e929e15b55c184e451)
  # to include that functionality. So we need to install from their Github repo,
  # referencing that patch
  - name: https://github.com/ngine-io/ansible-collection-vultr
    type: git
    version: dcb398fccc8ba5b1ed0259e929e15b55c184e451