collections:
  # Install a collection from Ansible Galaxy.
  - name: hetzner.hcloud

  - name: community.general

  - name: community.digitalocean
    version: "1.1.1"
  
  - name: ngine_io.vultr
    version: "1.1.0"