---
- name: Setup Digital Ocean public Monero nodes
  hosts: digitalocean_nodes
  gather_facts: False
  user: root
  vars:
    - do_api_key: "{{ lookup('env', 'DO_API_KEY') }}"
    - public_ssh_key_name: "{{ lookup('env', 'PUBLIC_SSH_KEY_NAME') }}"
    - public_ssh_key: "{{ lookup('env', 'PUBLIC_SSH_KEY') }}"
  roles:
    - digital_ocean_setup
    - volume_mounting
    - monero_user
    - network_dependent_vars
    - firewall
    - role: monerod_download
      vars:
        monero_user_home: "{{ result_user_creation.home }}"
    - role: systemd_service
      vars:
        monero_user_home: "{{ result_user_creation.home }}"