---
- name: Setup monerod
  hosts: 127.0.0.1
  vars:
    - monero_dir: /home/luis/Code/ansible_tests/monero
    - monerod_path: "{{ monero_dir }}/monerod"
    - data_dir: "{{ monero_dir }}/data"
    - network: "--testnet"
    - monerod_user: monero
  tasks:
    - name: Ensure monerod_user exists
      become: True
      user:
        name: "{{ monerod_user }}"
        system: True
        create_home: False
    - name: Ensure monero directories exist
      become: True
      block: 
        - file:
            path: "{{ monero_dir }}"
            state: directory
            owner: "{{ monerod_user }}"
            group: "{{ monerod_user }}"
            mode: "777"
            recurse: True
        - file:
            path: "{{ data_dir }}"
            state: directory
            owner: "{{ monerod_user }}"
            group: "{{ monerod_user }}"
            mode: "777"
            recurse: True
    - include: ./plays/setup-network-dependent-vars/setup-network-dependent-vars.yml
    - include: ./plays/set-up-firewall/set-up-firewall.yml
    - include: ./plays/download-monero/download-monero.yml
    - include: ./plays/setup-service/setup-service.yml
