---
- name: Setup monerod
  hosts: 127.0.0.1
  vars:
    - network: "--testnet"
    - monero_user_name: monero
  roles:
    - monero_user
    - network_dependent_vars
    - firewall
    - monerod_download
    - systemd_service