---
- name: create init script
  # become: True
  template:
    src: start_monerod.sh.j2
    dest: "{{ monero_volume_mountpoint }}/start_monerod.sh"
    group: "{{ monero_user_name }}"
    owner: "{{ monero_user_name }}"
    mode: "775"
  register: result_init_script

- name: create service file
  # become: True
  template:
    src: monerod.service.j2
    dest: "{{ services_dir }}/monerod.service"

- name: create ban list
  # become: True
  when: "ban_list"
  get_url:
    url: ban_list
    dest: "{{ monero_volume_mountpointe }}/ban_list.txt"
    group: "{{ monero_user_name }}"
    owner: "{{ monero_user_name }}"
    mode: "774"
  register: result_ban_list

- name: Restart service monerod
  # become: True
  systemd:
    name: monerod
    state: restarted
    enabled: True
    daemon_reload: True