---
- name: create ban list
  when: "ban_list_url"
  get_url:
    url: "{{ ban_list_url }}"
    dest: "{{ monero_user_home }}/ban_list.txt"
    group: "{{ monero_user_name }}"
    owner: "{{ monero_user_name }}"
    mode: "774"
  register: result_ban_list

- name: create init script
  template:
    src: start_monerod.sh.j2
    dest: "{{ monero_user_home }}/start_monerod.sh"
    group: "{{ monero_user_name }}"
    owner: "{{ monero_user_name }}"
    mode: "775"
  register: result_init_script

- name: create service file
  template:
    src: monerod.service.j2
    dest: "{{ services_dir }}/monerod.service"

- name: Restart service monerod
  systemd:
    name: monerod
    state: restarted
    enabled: True
    daemon_reload: True
  changed_when: False  # otherwise restarted always reports "changed"